//
//  ToursUIViewController.swift
//  Craft Beer Map
//
//  Created by Gregory Lavery on 03/08/2015.
//  Copyright (c) 2015 Gregory Lavery. All rights reserved.
//

import UIKit

class ToursUIViewController: UIViewController, UITableViewDataSource, UITableViewDelegate {
    

    @IBOutlet weak var tableView: UITableView!
    let textCellIdentifier = "ToursCell"
    let arrayTours = ["Pickle Tours", "Pub Crawlers", "Evening Out"]
    var toursData:[(toursName: String, toursLocation: String, toursInformation: String)] = []
    var swigData:[(swigName: String, swigImage: String, swigLine: String, swigDate: String, swigReview: String)] = []
    
    func tableView(tableView: UITableView, cellForRowAtIndexPath indexPath: NSIndexPath) -> UITableViewCell {
        
        let cell = tableView.dequeueReusableCellWithIdentifier(textCellIdentifier, forIndexPath: indexPath) 
        let row = indexPath.row
        cell.textLabel?.text = swigData[row].swigName
        return cell
    }
    
    func tableView(tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return swigData.count
    }
    
    func numberOfSectionsInTableView(tableView: UITableView) -> Int {
        return 1
    }
    override func viewDidLoad() {
        super.viewDidLoad()
        tableView.delegate = self
        tableView.dataSource = self
        setUpTuples()
        
        // Do any additional setup after loading the view.
    }
    func setUpTuples(){
        createLocalVersion()
        toursData.append((toursName: "Pickle Tours",
            toursLocation: "Pickle Tours",
            toursInformation: "http://www.victoriaharbourferry.com/tours-services/pickle-pub-crawls"))
        toursData.append((toursName: "Pub Crawlers",
            toursLocation: "Pub Crawlers",
            toursInformation: "http://PubCrawlers.com"))
        toursData.append((toursName: "Evening Out",
            toursLocation: "Evening Out",
            toursInformation: "http://eveningout.ca"))
        
    }
    override func prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject!) {
        if (segue.identifier == "segueTours") {
            let svc = segue.destinationViewController as! ToursDetailViewController;
            if let currentIndex  = tableView.indexPathForSelectedRow?.row {
                svc.swigName = swigData[currentIndex].swigName
                svc.swigImage = swigData[currentIndex].swigImage
                svc.swigLine = swigData[currentIndex].swigLine
                svc.swigReview = swigData[currentIndex].swigReview
                svc.swigDate = swigData[currentIndex].swigDate
            }
        }
    }
    
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    func createLocalVersion(){
        var swigReviews: [String]=["Ayinger Altbairisch Dunkel","wp-content/uploads/2014/02/Photo1-1024x682.jpg","Some say that his best friend in grade school was a half eaten fish. Weird. All we know is, he's called The SWIG!","On 18 Feb 2014","A gorgeous brew from an unfortunately located brewery, if Munich Oktoberfest is the social event of the season.  If you do not know, in Munich, it is.  So now that The Swig has forced you to ask a question, I will await your PM.  Until then, onto beer.  This Dunkel is dark as it is expected, yet when holding the glass in front of light we get a golden reddish clarity.  Does that work?  Yeah it does.  It is an emotional colour.  The aroma is caramel, with slight coffee and roasted malt flicking the nose tip yet no apparent hop aroma.  The taste is true bottom fermented goodness mixed with caramel and roast.  The roast flavour quickly disappears, but the caramel remains behind causing your tongue to crave more.  This is a great session brew that is both enjoyable and drinkable, and would be great sold in a six pack.",
            "Barque Belgian Golden Strong Ale Lighthouse","wp-content/uploads/2015/03/lighthoues-barque-copy-1024x682.jpg","Some say he once wrestled a Wooly Mammoth to the ground and that he can time travel. All we know is he's called The SWIG!","On 8 Mar 2015","Another new offering from Lighthouse brewing to tempt all our palates.  Barque is a Belgian golden strong ale delivered as the latest member of their Uncharted series.  The label is a new approach with elegant font and a lot of swooshes and swirls that remind me of filler for tattoo sleeves yet I imagine were used to mimic water and waves.  The beer pours a burnished gold with a pearl white foam that unfortunately dissipates rather quickly.  The aroma is phenolic and characteristic Belgian with a subtle yet dominant candy nose.  The taste is rich, sweet, and juicy with some malty candy and a welcoming bitterness into the finish.  It is surprising that this brew is 8+% alcohol due to its smoothness and drinkability, yet there it is.  Lighthouse did a good job of this one and I hope they keep delivering new brews.",
            "Bear Republic Racer 5","wp-content/uploads/2014/02/Bear-Republic-Racer-5-1024x682.jpg","Some say his wizardry is spot on, but that he is failing alchemy. All we know is, he's called The SWIG!","On 26 Feb 2014","This brew is touted as a quintessential brew of the iPA class. Practically royalty.   Served in a classic bomber bottle and old school cartoon label, it definitely looks more amateur than it tastes.  The colour is a deep amber to almost orange with a good strength foamy head.  A floral bouquet hits the nose as well as major citrus character of the West Coast persuasion. I sense some C’s from the Hophood: Centennial, Cascade, Cluster, Chinook, etc but something in there. Yeah WEst Coast! The brew enters the oral cavity easily and is welcome, then takes it’s time to leave.  This is a chewy, boozy, grainy, and malty beer.  Sweetness upfront and a strong balanced bitterness.  There is a great middle flavour of coastal hoppy goodness that smooths out the palate all the way to the finish. It is a great and bold IPA that admittedly would have been much better fresh, but it still was highly drinkable and enjoyable.",
            "Brasserie De La Senne Taras Boulba Extra Hoppy Ale","wp-content/uploads/2013/12/Photo1-1024x682.jpg","Some say he is, and that also he isn't. All we know is, he's called The SWIG!","On 18 Dec 2013","This time around The Swig went international.  A brew out of Brussels, Belgium was tested and found to be a little difficult to understand as will be explained below.  On the other hand, i have no trouble explaining Taras Boulba, a great story, and if you can check out the movie Taras Bulba (different spelling) featuring Yul Brynner and Tony Curtis for a more clear view of this dramatic tragedy, I highly recommend it.  Now back to the important part, the beer. Taras Boulba is a hoppy low alcohol Belgian Pale Ale brew of 4.5%.  It pours a striking hazy opaque amber colour with a substantial and sustaining pure white foam. The aroma is forced out of this highly effervescent beer and comes across as spicy and grassy, and unfortunately oxidised.  So we will salvage what we can from what the unfortunate packaging has stolen. The taste is minimal yet smooth in the start with very little flavours until a blast of hops hits with clinging bitterness.  If you are trying to place this is in a style to help understand it better, don’t bother.  Enjoy it for what it’s worth like Buffalo Springfield suggests, because it can be a session IPA, a hoppy wheat, a Belgian session wheat IPA, etc and huh?  As for “Smeirlap!”, it means “Fool” in the local Belgian dialect.  It is being said by Taras Boulba himself to reflect the tragedy of his son’s love for a female Taras does not approve of.  Go enjoy! Thanks Brasserie De La Senne!",
            "Brouwerijdemolen Dubbelbock","wp-content/uploads/2014/02/Brouwerijdemolen-Doppelbock-1024x682.jpg","Some say he built a stealth bomber out of lego, and that he's invisible on Thursdays. All we know is, he's called The SWIG!","On 4 Mar 2014","the fella that started this brewery has some great marketer working for him because I am seeing his brews in more places than ever.  I must also say that the variety they put out is wondeful.  I managed to grab a Doppelbock, although it was past it’s best before date.  This bothered me at first but since I already had it I figured, why not? Let’s Swig! The busy label has style and because of that it is acceptable and clever and stands out prominently.  The brew poured a deep dark brown with a nice tan head filling the glass. I was getting excited, because once you go Bock… My favourite.  The nose was sweet toffee and alcohol attached to a lingering grainy and bready smell.  This was a full meal inhale and I immediately went in for the taste.  This was a warming experience, laced with alcohol warmth, and balanced between a medicinal or noble hop aroma and a caramel sweetness.  The body on this beer was all curves with a finish warm (did I mention this beer was warm), and loving. I would definitely buy another three and enjoy.",
            "Cantillon Gueuze 100% Lambic Bio","wp-content/uploads/2014/01/Cantillon-1024x682.jpg","Some say he has formal training as a maestro and that his left foot is webbed. All we know is, he's called The SWIG!","On 27 Jan 2014","Ahhhh beer. French beer. What pops into that hophead of yours when you hear that? My thoughts were saison and that’s what you get here. Cantillon Gueuze is one of those prestigious brews that the beer geek world over knows of and respects whether they have tried it or not. It has that mystique Cantillon does. That panache and prestige that many brewers strive for and desire. Let’s pour in. The bottle was a baby champagne bottle with cork and oxygen scavenging bottle cap that all together added so much to this brew. Next there is the label with the little boy having a pee while holding a brew, a sidebar that says ‘good until 2030′ (now that is commitment), and you have a memory in hand. Pouring this brew out was pretty to watch. A pale yellow colour fills the glass with a coarse foam disappearing as the pour continues. The nose was- I can say this because i spent time on a prairie farm- farmyard. Grassy, earthy, dank and musky co-mingled to deliver a bouquet to the nose that would have been thrown at a barnyard wedding. The taste was ever so acidic and lemony yet with a tart, dry, and really cidery sharpness. There is a lingering sensation on the tongue that reminds me of grapefruit without the flavour. The finish was tart and puckering that remained long after the bottle was empty. That was a great experience. Merci Cantillon, Cheers!",
            "Category 12 Unsanctioned Saison","wp-content/uploads/2015/01/IMG_442382530-1024x682.jpg","Some say his eyelids are elastic and that he can dice a watermelon in 4 seconds flat. All we know is he's called The SWIG!","On 8 Jan 2015","Firstly, we would like to welcome the newest kid on the Vancouver Island block.  Hello and congratulations Category 12!  Now the important part of this post, the brew. Unsanctioned Saison is presented in a standard bomber bottle, the ideal serving size.  The artwork is reminiscent of something from the mid 20th century with bold lines and rich colouring, while the comic nature is eyecatching and fun.  Unsanctioned pours a vibrant red-orange, something that you would see in a sunset.  The head does not stick around, but the aroma is earthy and crisp.  The taste is spicy and rich with some banana and fruit cocktail.  There is a suitable amount of bitterness, and even better, a wonderful hop flavour in the mid-sip. This is an enjoyable brew, and I imagine that it will get even better.  Thanks everyone at C12.",
            "Central City Imperial Porter","wp-content/uploads/2014/12/CC-swig-imperial-porter-1024x682.jpg","Some say he taught Jimi how to play guitar and that he's got webbed toes. All we know is, he's called The SWIG!","On 21 Dec 2014","This is a classy brew. The colour is dark as a night museum, and glows ruby through light, but only just. I love the richness of the taste with treacle, caramel, and some hot sugar giving it a slight burning flavour that Ralph would appreciate. There is a robust wood flavour throughout that gives this tasty libation winy character along with some solid oak flavour. The roasty and fruity body is huge and I would gladly consume this beer over and over.",
            "Coronado Stupid Stout","wp-content/uploads/2014/02/Coronado-Stupid-Stout-1024x682.jpg","Some say he has a dog that is part T-Rex and that he doesn't believe in aluminum. All we know is, he's called The SWIG!","On 11 Feb 2014","Coronado delivers their beer in a bomber size painted bottle that is good to look at and good to see that there is some money spent on cool packaging.  I am looking forward to this one since it is the first I have had from them.  The pour is thick and dark and a nice head settles to the rim.  There is a lovely roasty smell as would be expected yet it has a certain fullness and slight alcoholic aroma. The taste of this beer was simply delicious.  Chocolatey tongue warming sweet stout with a slight acrid taste.  Also at the front is sherry flavours suggesting a touch of oxidation.  This is a slick and easy to drink roasty brew.  Hints of coffee, grainy cereal, and biscuit fill out the middle swig.  This is all followed by a light finish that made it thoroughly awesome.  Thanks Coronado.",
            "Crew Republic Drunken Sailor IPA","wp-content/uploads/2014/10/crew-republic-ipa-1024x682.jpg","Some say he's terrifed of pickles and that he's never once tied his own shoes. All we know is, he's called The SWIG!","On 23 Oct 2014","As a one time sales rep for many of the big US craft breweries, I met some great people on my rounds in Victoria.  And along the way I stumbled upon some brilliant and very, exotic inventories. After chatting with my pal Tomo at Metro Liquor and looking their shelves up and down for a spell, I came across the Crew Republic IPA.  As it was explained to me, Crew Republic is a German Brewhaus focusing on “traditional” North American style beers.  I suppose we could get into an argument about how old something has to be before it can be called “traditional” but let’s just say that it works in this case. This beer pours a thick and viscous ruby colour.  It had a beautiful sounding “glug-glug” as it came tumbling out of the bottle and into my glass.  With a rich, herby and slightly spicy nose, it’s got an all too delicious faint cherry booziness to it. I’m pleased to say it’s not overpoweringly bitter, and its quick and punchy finish is to my liking also.  I will definitely head back to where Crew Republic sits in the beer fridge and pick up a few of their other offerings.",
            "Driftwood Crooked Coast Altbier","wp-content/uploads/2014/06/crooked-coast-1024x682.jpg","Some say he subscribes to 'Leaf Collecting Magazine' and that he failed grade 5 PE. All we know is, he's called The SWIG!","On 24 Jun 2014","So the Swig and I were at the pub… and I asked him to chat about his beer.  This is what he had to say.  (Yes, he orders two at a time.) Crooked Coast Altbier is one of the only takes on this style on the entire coast.  It is great that someone tries to emulate such a wonderful style from the great brew nation of Germany, and I am glad we have a fresh Coastal version to try.  This beer pours slightly cloudy with a reddish copper colour into my pint glass.  The foam lingers for a bit before leaving the beer open.  The nose is fruity, with slight apples and pears, and a nice herbal noble hop note. The taste was mild and slightly estery to the tune of herbal bitterness and roast mixed with sweetness from the malts and cola character.  The beer was exceptionally dry, and due to the high carbonation it came off very thin although crisp and clean.  This will be great for the Summer as the bottle label invokes and a patio is a great place to appreciate this one.",
            "Driftwood Lustrum Wild Sour Anniversary Ale","wp-content/uploads/2013/11/Driftwood-5th1-1024x682.jpg","Some say he can kill a man with a Chiquita Banana and that he's hooked on phonics. All we know is, he's called The SWIG!","On 13 Nov 2013","Driftwood has delivered a sour Anniversary brew for us to enjoy.  It is in the usual bomber size with highly attractive label. Visually the brews always have great appeal on the shelf.  The beer is a majestic burgundy red colour topped with a wonderfully persistent pink foam.  How did they get that colour?  Smiles abound looking at this beer.  Something wonderful and hopeful.  The nose is berry fruit and sharp.  It was aged in oak with black currants and I now know this is a nice pairing.  The taste is warming and crisp with a dominant sour taste reminding me of a barn, but a nice crafty clean one and not a dirty messy sloppy one.  The alcohol is hidden behind sour fruit and bush berries.  That flavour of picking straight off of the bush and making that puckering face is all happening with Lustrum.  There is a hint of arugula in the spiciness and also only a hint of bitterness.  It’s weird but I feel my teeth love it. This brew is awesome really and should be shared.  Thanks Driftwood and Happy Anniversary!",
            "Fresh Hop Shootout 2013!","wp-content/uploads/2013/10/FH-Shootout-1024x682.jpg","Some say he's Ultimate Warrior of Ultimate Frisbee and that he's never worn a hat. All we know is, he's called The SWIG!","On 29 Oct 2013","One fine day a plan was hatched to taste the fresh hop beers that were available and see how they compared to each other and this up and coming independent ‘style’.  It was a good idea because the fresh hop character in brews varies quite a bit due to the methods of how they were utilized.  Also it was a great idea to taste beer on a Saturday afternoon, because it was beer.  At any rate here we go! Hoyne – Wolf Vine Pale Ale The beer poured a great orangey copper colour that was quite brilliant.  The aroma was alive and fresh with a green and vinous scent reminiscent of a florist.  Tasting the brew brought a smile to the face.  That does sound strange, but the brew was very well put together.  It was full bodied with a spiciness near the end that tingled the throat like a fizzy candy. There was woody character, medicinal flavours, and a very herbal nose served in a noble hop feeling.  These flavours were cut nicely by the strongly bitter hoppiness.  Overall, a great pale ale brew with balance. Thanks Hoyne! Phillips – Green Reaper IPA Green Reaper came up next and poured a powerful deep yellow colour.  The fresh hop character- that was almost too fresh- was very prominent.  It smelled piney, resinous, and… foresty!  It was like a hike on Elsie King trail or Goldtsream. The brew was full bass with a yeasty and hoppy nose, but not overwhelmingly aromatic or too trebly.  Meaning there was a good balance without too many edges.  For a 6.5% brew it was exceptionally easy drinking and was a very decent IPA. Thanks Phillips Crew. Lighthouse – Road Trip Dark Ale The first offering from Lighthouse in the fresh hop categaory ever.  A dark fresh hop brew… what?  Guess someone had to do it eventually.  The smell was sweet and roasty with a lifting fresh hop aroma of herbs and life.  Wow is it easy to drink. It makes me think of a lager showing up to a winter cask festival because it is not the typical brew to show up, but it is most welcome and a relief.  The colour is black cherry with a malty toffee caramel presence heading up the nose.  It was very pleasant, drinkable, and sharable. Thanks Lighthouse!",
            "Great Canadian Beer Festival 2015","wp-content/uploads/2012/12/Swig-Fix-1024x682.jpg","Some say he prefers briefs to boxers and that his iPad has 1000% battery life. All we know is, he's called The SWIG!","On 10 Sep 2015","Cheers to all the breweries, brewers, organizers, volunteers, food trucks, musicians, entertainers and craft beer fans for making The Great Canadian Beer Festival such a hit year after year.  And as always…. Be excellent to eachother at BeerFest this year and get home safely. Cheers!",
            "Sierra Nevada Hoptimum Whole Cone Imperial IPA","wp-content/uploads/2013/07/Sierra-Nevada-Hoptimum-1024x682.jpg","Some say he has an uncredited voice role in Charlotte's Web and that he can hold his own when drinking with Chuck Norris. All we know is he's called The SWIG!","On 15 Jul 2013","We do not get as many American beers up North as we’d like so this biggie was nice to try. This is a huge beer.  The beer smells alcoholic and grainy but tastes juicy and hot. Woo boy. Bang for buck on this feller i think, because although it is labelled imperial IPA with whole cone hops and care, to me it lacks complexity. You get heat, juicy, malty, bitter and boozy but there is no cohesiveness. All that said, it punches like a heavyweight. Thanks Sierra Nevada for the experience.",
            "Howe Sound Wooly Bugger","wp-content/uploads/2014/02/Howe-sound-wooly-bugger1-1024x682.jpg","Some say he's the leader of a large squirrel army and that his biggest fear is tape. All we know is, he's called The SWIG!","On 14 Mar 2014","This is just a baby size beer from these BC boys, yet it packs a high abv and flavour ka-chow for you.  Howe Sound runs the table with styles which is wonderful for a craft drinker.  Like most barleywines, Wooly Bugger, pours a brown colour with the head quickly disappearing.  The aroma was alcohol, warmth, and some graininess to accentuate the sweet malty character.  Now the taste.  Well. Hold on kids.  The taste is beyond normal. Wooly Bugger (i should really look up why they chose such a strange-pictures-to-my-imagination moniker for this brew) tastes like a malt salad.  Like all salads you throw in a little this and a little that and end up with a symphony of ingredients yielding a glorious composition. My mouth is working for this one because it is heavy and chewy. I taste dark fruit notes and delicate caramel.  I get raisins, dark fruit bread, and a Ukrainian favourote, compote.  Malty malty malty!  Is that a touch of smoke i get? It adds such complexity and wonder. How can I say anything bad about this wonderful take on a brew? Thanks Howe Sound for a great beer.",
            "Hoyne Entre Nous","wp-content/uploads/2014/07/Entre-Nous1-1024x682.jpg","Some say he has the worlds largest seatbelt collection and that he once raised an ox. All we know is, he's called The SWIG!","On 25 Jul 2014","The Hoyne Entre Nous Belgian Cherry Witbier follows represents a refreshing style of beer that screams Summertime.  The cherry wit has a precious colour of the raspberry lemonade persuasion and a clarity that is quite thorough.  Although the stark white foam is fairly short lived it was nice to see. The nose has a fruity flavour that reminds me of plum and cherry skin, but there is also something plasticy.  Weird but true.  The Swig is to the point.  General fruit and a hint of cherry dominate, but are in fact only undertones.  The slight sweetness also plays a minor role in the cherry wit. The beer is dry as it should be yet a little too thin.  It is a refreshing sip up front and at the standard alcohol level of 5.1% I am sure this brew will refresh people.  It is a good beer. Thanks Sean.",
            "Hoyne Falstaff Ale","wp-content/uploads/2013/12/Hoyne-Falstaff-Swig-1024x682.jpg","Some say that he sleeps inside out and that instead of pictures, he hangs spoons on his walls. All we know is, he's called The SWIG!","On 10 Dec 2013","Wow what a treat for the Swig! How many bottles of this brew were available?  You are looking at it.  It is truly fortunate that the Swig managed to snag one from the great and powerful brewer and business owner Sean Hoyne. Cheers! Falstaff pours a beautiful deep brown with highlights of subtle red that you can almost see a fire crackling through. A quiet aromatic crown releases a treble of chocolate and roasted aroma.  The first taste was a triple treat.  Up front there was just enough sweetness to counter the neutral bitterness and strongly bubbling sensations.  The midsip really exemplifies the body of this malty beauty while grassy aromas percolate thru the liquid layer on your tongue.  Their is an interesting breathlessness in the flavour that may be the child of a special hop or yeast.  Overall this brew was highly sessionable and would have been a fitting quencher for anyone singing their heart out at the Opera.  Thanks Sean.",
            "Phillips Kaleidoscope Mosaic IPA","wp-content/uploads/2013/07/Phillips-Kaleidoscope-IPA-1024x682.jpg","Some say his dog only runs backwards and that his coat is gravity repellent. All we know, is he likes to SWIG.","On 17 Jul 2013","Hey Phillips, another one? We are spoiled around here for sure with all your releases.  This beer comes in a cool new bottle with a stylishly embossed slim neck. Bravo.  It pours out with an elegant and more deeper colour than I would have expected; kind of like apple juice or a golden orange. The aroma is  power power.  Big aroma!  It keeps giving a strong acidic citrus sharpness with what must be the guava as advertised but also something slightly unpleasant, vegetal. Sipping… First thought on that taste was ‘that can’t be it’.  Socks.  So I tried again.  Socks, but now with a cranberry bitterness. I feel it hooked up in the throat like a catchy tune.  It is really interesting but to me not terribly enjoyable. If this is Mosaic then I sure don’t know what all the rage was about. Serve this baby cold and share it.  Thanks again Phillips.",
            "La Vache Folle Imperial Milk Stout Microbrasserie Charlevoix","wp-content/uploads/2014/01/La-Vache-1024x682.jpg","Some say he sleeps curled up under the Christmas tree and that he's unaffected by gravity. All we know is, he's called The SWIG!","On 10 Jan 2014","When you have a picture of a cow on the label it usually means you are about to (hopefully) enjoy a milk stout.  To answer your question, yes indeed.  The brew poured a lovely brown liquor that you can tell is just a little more viscous than the average beer.  Topped with a darker brown head that maintained itself throughout the session, La Vache looked beautiful and inviting.  The aromatics reminded me of dairy and thick chocolate milk. A nice  alcoholic warmth wafting up was a nice feeling as well. The taste was lustrous, and it only improved as it warmed in my gloved hand. I began to detect some rum flavours mingled with the malty sweetness as the journey continued. Overall, a very drinkable brew that I would be happy to try again. Thanks La Brasserie Charlevoix.",
            "Lighthouse Desolation Oyster Stout","wp-content/uploads/2013/12/Lighthouse-desolation-1024x682.jpg","Some say he buys lollies for monkeys and throws only the first stone. All we know is, he's called The SWIG!","On 16 Dec 2013","Lighthouse has given us in Victoria something special in an Oyster Stout, and Imperial no less.  The beer pours really black with a dark brown foam that quickly disappears.  The nose is like a whiff of coastal wind with brine and freshness mixed with alcohol, raisin and a warming sensation.  The taste is sharp and salty, coastal, with caramelly burnt sugar coupled with that all-sorts liquorice candy your Grandma had on her coffee table.  This beer is highly complex and very flavourful.  It tastes almost like a barrel aged brew should but without the barrel aging unless we are not getting the full story.  Rightfully so, there is also a distinct oyster flavour that we are assured were definitely part of the brewing process.  Desolation is smooth, easy drinking, highly interesting, and should be shared with a friend or two.  It is startling to think this brew is 9.3%, and I suggest it might do something interesting after a year of cellaring.  Thanks Dean.",
            "Lighthouse Fisgard 150 Bavarian Lager","wp-content/uploads/2013/10/fisgard-1024x682.jpg","Some say he can do a 360 kickflip on a wheelbarrow and that he's triple jointed. All we know is, he's called The SWIG!","On 9 Oct 2013","Lighthouse Fisgard Bavarian Lager - A nice holding bottle of standard size and simple design.  The brew pours straw yellow and with a nice little foam on it.  The aroma is quite nice for a light lager, even though it is a Bavarian Lager.  Funny how us Canadians try so hard to recreate other countries brews. This explains the noble hop aroma and following clean lager taste. There is a slight papery texture with great noble bitterness and no lingering aftertaste.  A nice tang on the tongue lingers with the pleasing pleasant flavour.  Thanks Lighthouse",
            "Lighthouse Seaport Vanilla Stout","wp-content/uploads/2014/11/seaport-swig-1024x682.jpg","Some say he's a true master of the accordian and that his pet bunny's name is hops. All we know is, he's called The SWIG!","On 22 Nov 2014","Lighthouse has cleaned house of late and provided all of us with some new eye candy to pair with their award winning brews.  This new and latest offering from them seems to follow their sweet dark brew trend having already put out a sweet stout in Keepers and a dark chocolate porter.  The new label is quite attractive and the colours are grabbing in the tan and brown.  Hopefully this Explorer Series can keep delivering interesting new brews.  The brew pours tan and effervescent, with an attractive deep brown colour. The nose is chocolate roast with a nice vanilla draft leaping from my glass.  The taste is highly vanilla and roasty with lingering bitterness.  The body is mid-range and  suits this brew nicely.  I’m not sure if it is intended to be a sweet or dry stout but I like it for what it is, good and tasty.  I would drink this one with dessert and even use it to make cookies! Thanks Lighthouse!",
            "Listen all y'all it's a SABOTAGE, VIB","wp-content/uploads/2014/08/sabo-1024x682.jpg","Some say he has solar powered taste buds and that he's related to George the Animal Steel. All we know is, he's called The SWIG!","On 30 Aug 2014","Vancouver Island Brewery has stepped away from the comfort of the standards and delivered a brew worthy of the craft movement. Sabotage not only has a funky coloured label, the artwork is sinister and fresh for one of the older breweries round these parts.  The Swig is glad that you can teach an old dog new tricks. The beer pours a cloudy amber with a nice snow white foam. The nose drifts a fairly nondescript hoppy character that feels resiny, tropical, and a little character like fresh hop, which was interesting and not possible. The taste is juicy, resiny, fresh, and again that green hop character.  Sabotage has a great hop flavour, and the right amount of cloudiness for a strongly hopped brew, but there is a slight malfunction in a hint of dishwater or soapiness on the tongue. Luckily there is a lingering, dry bitterness that soothes the palate like novocaine making this beer especially drinkable and any other issues forgetful.  Thanks VIB! Keep growing, please.",
            "Mill St. Cobblestone Dry Irish Stout","wp-content/uploads/2013/10/cobblestone-1024x682.jpg","Some say that he is the reigning world champion for rolling a loop with a stick and that his eyelashes are pure titanium. All we know is - he's called The SWIG!","On 14 Oct 2013","This brew comes in a big can.  Why don’t we get more of these round here? I love this serving size.  Immediately I get a mysterious nose that feels like Burgundy and juicy cherries.  It is a constant aroma and its flavour is dry and roasty yet somehow thin.  As dry stouts go  this is a great tasting low alcohol beer.  The type of beer that Industrial lager drinkers think of when they say “I don’t like dark beer”.  This beer would go great with foods that pack heat or other warm stuff.  Thanks Mill St.",
            "Phillips Monkey Drummer and the Incomplete Octave 12th Anniversary Ale","wp-content/uploads/2013/08/Phillips-12yr-Anniversary-1024x682.jpg","Some say he's an expert knitter and that he discovered the Lanthanide series of elements. All we know is he's called The SWIG!","On 13 Aug 2013","Phillips Monkey Drummer and the Incomplete Octave 12th Anniversary Ale - The Phillips flywheel has spun another brew off for our enjoyment and this time it is a celebration of 12years.  Happy Anniversary Phillips!  Congratulations Matt.  Big beer for a big year.  It has a fresh apple and citra-like nose.   I like this nose, it is really good.  Drinking this beer is a different story.  It is heavy as finding out your girlfriend of one month is pregnant.  Take a bite and chew on this is a better recommendation than taking a swig.  It is boozy warm during and long after.  Flavours are tough to isolate due to the massive alcohol, sorry.  This  beer needs to be shared with four others so that you can all breathe fire on each other.  I think you could have gotten away with selling this in standard bottles, because my swigging partner and I barely finished even half of it. Thanks Phillips.",
            "Moon Under Water Pott's Pils","wp-content/uploads/2014/05/moon-potts-pils-1024x682.jpg","Some say that his tears are adhesive and that if you insult his mother he will headbutt you in the chest. All we know is, he's called The SWIG!","On 13 May 2014","Moon Under Water Pott’s Pils Summer is here in Victoria.  Not technically, yet everyday feels full of promise of more.  That is why the Victoria famous Pott’s Pils is a fine way to kick off this season.  The Moon Under Water is a stronghold for German styles, and I am possibly one of the happiest and hugest fans of this place.  Though I confess I do not Swig their often enough.  I have enjoyed this brew before but have not registered a review, and since my adoring public requires it, I will deliver it. The Pils style- in this case German Pils (2A)- is characterised as a crisp, fresh brew with slight noble spicy hop character and some graininess from the Pils malt. Clay delivers on all these requirements.  Ahhhhhhh… the scent of a great lager nose.  The oh so pale colour to the point of almost green is fantastic.  That slight maltiness with a touch of sulfur in the aroma being delivered ever so slowly through that fluffy white foam.  The fruitiness is present as pear and general subtle fruit basket. The taste is crisp and fresh up front.  There is also a watermelon juiciness and a Kool Aid satisfaction.  From mid sip on we get strongly bitter and a pleasant tasty lingering flavour.  This brew is so easy to drink, and there is nothing hanging in your mouth that you don’t want. Thanks Clay!",
            "Hoyne Off The Grid Red Lager","wp-content/uploads/2013/07/Photo-1024x682.jpg","Some say that his genitals are on upside down and  well that's pretty bad. All we know is, he's called The SWIG!","On 9 Jul 2013","I tell you what.  I tasted this one with intentions of a small glass and judgement.  Initial thoughts were nice body, great red colour, and great full lager scent.  Just what the brew promised.  Then I noticed a hint of earthiness and graininess which really gives the label some cred.  Off the Grid is easy drinking and smooth, which gets easier drinking cold and by a fire. My glass kept refilling and I ended up finishing the bottle.  I probably would have finished another too.  Like those snacks and sandwiches at High Tea, it isn’t outstanding, but it certainly is easy to finish. Thanks Hoyne.",
            "Parallel 49 Hoparazzi","wp-content/uploads/2013/10/photo-1024x768.jpg","Some say he a direct descendant of Andre the Giant and that he once drop kicked a Stegosaurus. All we know is he's called The SWIG!","On 3 Oct 2013","A new style of beer emerging is this type of India Pale lager.  This beer comes in a great solid bottle and a cartoony label.  Not my style for art but my medium is beer, not colours and drawing. The pour is nice and smooth, with a very pale beer to show for the effort.  The smell is slightly flowery and generally hoppy, but otherwise nondescript.  The taste is fairly busy where I detected a juicy mouthfeel, and strong alcohol.  It is definitely hoppy, and there is also woody and papery lager characteristics up front and IPA rounding it out.  Blending of styles is a cool fun idea and Graham seems  to have accomplished what he set out to do with this one.  Hoparazzi has good taste that feels like session brew, but it is 6% so…. check yourself before you wreck yourself.  Thanks Parallel 49.",
            "Parallel 49&#8242s Filthy Dirty IPA","wp-content/uploads/2014/12/filthy-dirty-IPA-vicbers-1024x682.jpg","Some say his fingertips are barbed like Spider man and that his sweat can clean precious metals. All we know is he's called The SWIG!","On 7 Dec 2014","This bottle is the standard at Parallel 49, and I love how substantial it feels. Like each and every time it promises something good awaits inside just for you. The bling pig with attitude is a bit strange even for a brewery that put a dude with watermelon teeth on a label.  It is what’s inside that counts though so here we go. The brew is a little more hazy than I like, but it has a gorgeous orange colour.  The nose is general floral hop mixed with some citrus, and is pleasant and not overpowering. The taste is juicy and slightly grainy with a hoppy bitterness lingering into the finish.  It is a great quick hit IPA that hits all the requirements without getting complicated.  The danger is that it is easy to quaff and it’s a 7+% brew.  Watch out folks. This does make a person happy to enjoy something filthy and dirty.  Thanks Graham.",
            "Phillips 13 Knots 13th Anniversary Ale","wp-content/uploads/2014/10/Phillips-13th-anniversary-hangmans-noose-1024x682.jpg","Some say he has backwards elbows and that he hands out batteries for halloween. All we know is  He's called The SWIG!","On 2 Oct 2014","Happy Anniversary to Matt Phillips and the Crew!  Congratulations and well done.  You are not the oldest, but you are most certainly the most well-known here inYYJ.   It seems Phillips gets the lion’s share of reviews on this site, and that’s only because they seem to be the only brewery putting out new brews on a regular basis.  So come on YYJ breweries let’s fill those shelves! 13 Knots is the Anniversary brew.  It comes in two parts meant to be as one.  The reason they could not do it in one unit is that the strength of the brew of their target  13% is illegal unless you are a distillery, and at the moment they are still only a brewery.  I suppose the right thing to do for a reviewer is three parts then so lucky you I care about what I do. The 13 Knots base is an Imperial IPA, which on its own is still aa formidable beverage at 11.9%.  I feel like a pansy issuing a warning yet here i go… This is a bottle of wine folks.  You share bottles of wine so please be responsible with this brew.  The taste is heavily acetone, phenol, and juicy fruit flavour. A mixed bag really.  The flavour of it is quite relaxing with its pine and citrus and hops hops hops.  It is very boozy, but what else can it be, right? The Hop Drop is a tougher one to handle.  Now I am not a spirits guy, that’s my friend the Boozedonkey’s realm, but I would say this liqueur was tasty and too young.  It is juicy and full of flavour and really a neat experience, yet I feel in time it would have come together better. Still, so cool.  No other brewery round here has done this. Finally, together at last, like Little Orphan Annie and Daddy Warbuck’s.  The moment we mixed and did a Mexican beer turnover the brew becomes hazy, and yep even more boozy. The brew actually smoothed out in mouthfeel, but got a little rougher in flavour country. The warning still stands especially not that we are in fact at 13% alcohol by volume.  The brew spirit has become slightly cantaloupey and fruit salad. True there is still a heavy acetone and alcohol aroma and flavour, but take this for what it is.  A big, bold, 13% Anniversary celebration or a brewery that has risen against most odds and triumphed.  Congratulations on 13 years, and I hope next year you go half-life!",
            "Phillips Crooked Tooth","wp-content/uploads/2013/09/Phillips-Crooked-Tooth1-1024x682.jpg","Some say when he makes it rain  it snows, and that he once built a lego deathstar in under 30 minutes. All we know is he's called The SWIG!","On 27 Sep 2013","Phillips Crooked Tooth Pumpkin Ale - I like the grippy shape of the bottle and fun artwork.  The aroma is very subtle here.  It’s kind of fragrant in the ‘bowl of fruity’ type way.  This beer taste starts with brown sugar and a sour pumpkin finish. Spice is really hidden but subtly there.  Gingerbready and very refreshing… Is this light beer?  It’s almost lager with some pumpkin taste.  Flavour country is more like driving thru a small town on the prairies but it is very drinkable.  Don’t know if this is what they were going for considering what is written in the bottle.   Thanks Phillips.",
            "Phillips Grand Barleywine 2007","wp-content/uploads/2014/02/Phillips-Grand-Barleywine-2007-1024x682.jpg","Some say he drinks himself sober, and that he already has the iPhone 13. All we know is, he's called The SWIG!","On 22 Feb 2014","Oh boy! What a treat! An old beer from Phillips!  Not just another new beer from Phillips, but a whole old one! This is truly a rare brew, and I am quite lucky to have had the opportunity to appreciate it. Up front, Thanks Phillips.  The Grand is a beautifully bottled barleywine complete with elegant label and shapely bottle.  The beer pours a gooey liquid brown with a touch a head yet!  True to style that quickly disappears leaving free and easy access to the liquid.  As I lift my glass to my lips my nose experiences caramel, sweetbreads, and warmth.  Can the nose be luxurious? In this case it is the best description. It brings visions of old wrinkled fruits dancing in my head.   My tongue plucks out what my nose has already found except now there is a beautiful body and bready malt flutters on my tastebuds. The sweet liquid holds to my tongue like honey rests on a counter and it is plesant and comforting.  This brew is very enjoyable. Very. It feels so well put together after it’s seven year rest.  Wow!",
            "Phillips Mass Extinction Ice Barleywine","wp-content/uploads/2014/02/Phillips-Mass-Extinction-1024x682.jpg","Some say he wasn't a virgin when he was born and that he once punched an orca. All we know is, he's called The SWIG!","On 10 Mar 2014","A Phillips seasonal is again available and like any self respecting reviewer, I got a copy.  The pour is a rich brown with minimal carbonation to interfere with the maltiness of this Barleywine.  The aroma was subtle malt and so I dove in.  The first sip was yummy, malty, juicy, chewy, and big.  Figs and toast.  Since it is iced, there is also an added cleanliness to the flavour.  Crisp and smooth.  There was an unfortunate tin can mid-sip in this brew though. Yet, the alcohol was warming and the finish was caramelly and toffeelike.  There must be bitterness in this one, yet it is tough to truly pick it out since the sweetness is so strong and the alcohol so potent.",
            "Phillips Octofox!","wp-content/uploads/2014/09/Photo2-1024x682.jpg","Some say he's impossibly good at crokinole and that he can prove 42 is an odd number. All we know is he's called The SWIG!","On 18 Dec 2014","Octofox is another IPA that was only in a hopbox but did well enough to get promoted to a bomber. The nose is tobacco and citrus, but more like the essential oil aroma from the peel and not the juicy fruit part. So it is more striking citrus and less soft.  There is also a detectable earthiness in it that reminds me of tea.  The colour is a lovely brilliant orange and is as clear as a Victoria Summer night.  The taste of Octofox is enjoyable.  The bitterness is nice on the finish and lingers like a good Pils would.  Their is a nice hop flavour as well of citrus, and well, the taste is almost sudsy and piney. Strange but it works.  This is a decent drinking beer that would probably be great on tap or on nitro to give it some creaminess.",
            "Phillips Short Wave West Coast Pale Ale","wp-content/uploads/2015/07/Shortwave-2-1024x682.jpg","Some say his wings are impervious to everything but water and that he loves standing in line. All we know is he's called The SWIG!","On 26 Jul 2015","I can’t help but feel Phillips has gone back to their roots a bit with this one.  It’s not filled with berries nor is it crazy hoppy.  It’s not barrel aged or a variety of multiple styles mashed together to form something new. This is a classic, super well balanced West Coast Pale Ale and I love it.  I think it’s one of their best beers since the Twisted Oak Red Ale.  (which I still hope to see again one day!) The Short Wave is now one of my standard fridge beers.  I still have a few Belgian Quads in there, but tonight it’s all about a busty malted pale with gentle bitterness at the fringes.  Drink up folks… I think this one is going to be around for a while. Kudos Phillips.",
            "Phillips Twisted Oak Rauch","wp-content/uploads/2014/04/Phillips-Twisted-Rauch-1024x682.jpg","Some say the SWIG is temporarily out of commission and that Matty's doing this one. All we know is... BEER!","On 27 Apr 2014","Phillips Twisted Oak Stillage Barrel Aged Rauch - Matt Phillips has been in the beer business for a lot less time than a few of the other locals yet he has firmly anchored his place as The West Coast brewery experience.  Not only does he have a presences at numerous events and concerts and goings on, not to mention some of the coolest designs for a brand around, he pumps out new beer after new beer for all of our enjoyment.  Today we tapped into another brew from the Twisted Oak series, a Rauch beer.  As the label says, Rauch translates to Smoke and this brew is  that.  The first Impression as i poured it out was that it had a most beautiful red colour.  The light reflecting thru made me think of a Victoria Sunset.  The nose is strong campfire with mushrooms, earth, and ham. The taste mirrored the aroma nicely, except now we add in some malty sweetness.  Midsip there is a fullness that made my mouth feel like it would not be able to hold all that in.  Good thing I have a big mouth.  There is a good sense of bitterness with a dry finish that leaves the mouth wanting more. There was some hints of whiskey as well but not much considering this was a barrel aged brew.",
            "Red Hook Audible Ale","wp-content/uploads/2015/04/audible-ale-opt-1024x682.jpg","Some say he can communicate with the dead and that he's a huge pop star in Zimbabwe. All we know is he's called The SWIG!","On 4 Apr 2015","Red hook describes this beer as “crushable” on the label.  Would I agree with this?  In a word…. Hell yes. As much as I consider myself a craft beer geek/junkie/enthusiast or whatever you want to call it…. I feel as though I’m a bit of an outsider.  And here’s why….  I LOVE pale ales, session beers and ISA’s. This beer is clean, simple, crisp, slightly grassy and yes, very drinkable.  My glass was empty before I knew it.  Good thing I have another one on deck.  I would visit this beer again in a heartbeat.  Especially now that summer is quickly approaching. Cheers!",
            "Red Racer Copper Ale","wp-content/uploads/2014/06/copper-1024x682.jpg","Some say he can crawl inside his own bellybutton and that he's never been on a Merry Go Round. All we know is, he's called The SWIG!","On 12 Jun 2014","This was a great beer to dust off the taste buds with. Copper Ale was served in a tall can which is my favourite serving vessel. The artwork was a throwback busy tattoo sleeve with our favourite Red Racer girl on it.  It poured copper which I initially felt before the name clicked in was a wondrous deep orange. The beer was crystal clear with a strong white foam.  The aroma was grainy and sweet with a hint of herbal hop.  The taste was so worth it.  Malty and grainy highlighted the predominantly Munich malt bill, and the mouthfeel was full garters and skirt- juicy and welcoming. This beer was rounded out nicely with a hint of bitterness, and could be enjoyed over and over again.  Overall, Copper Ale was a Perfect 10. Thanks Gary and well done!",
            "Red Racer ISA","wp-content/uploads/2015/05/Red-Racer-ISA-1024x682.jpg","Some say his times tables are different from everyone else's and that he's quite charming. All we know is he's called The SWIG!","On 16 May 2015","Summer is quickly approaching and the ever so ubiquitous ISA is hugely en vogue…. and I couldn’t be any happier. There is debate amongst beer geeks that ISA’s aren’t really even a thing.  The fact that they are simply a re branded version of the pale ale, and that ISA’s are hogwash. Kind of, sort of… maybe I guess.  I find a lot of true pale ales have a bit more malt to them, as IPA’s and ISA’s are less so, and quite hoppy.  So now what?  I say quit quabbling over it and go enjoy a pint…. whatever the hell you want to call it.  Just support your local breweries! Cheers!",
            "Rogue Beard Beer","wp-content/uploads/2014/02/Rogue-Beard-Beer-1024x682.jpg","Some say he grew up with 14 cats, and that he casts no shadow. All we know is, he's called The SWIG!","On 25 Feb 2014","A definitely unique beer is the easiest way to put it.  The more fun way to put it is after work one day when they were having a staff beer or two someone got a great idea, as happens in those situations, to see if their long time brewer’s beard had anything funky in it.  The idea built momentum like a snowball on a mountain and now we taste it.  Rogue Beard beer is the product and I will be honest here, it turned out about how I imagined something like this could.  The brew pours reddish yellow which is a strange combination unless you have an issue.  A large billowy head filled that glass and slowly allowed a Belgian character to escape.  The nose yielded a nice funky, wild yeast character to be more accurate, but to be more emotional, it was a pleasant general spiciness coupled with a gentle floral and stronger fruity character.   The taste is definite Saison, or “Shaveson”, in its fruitiness but without the lemony tartness of a true Belgian saison.  I guess that’s the beard coming thru.  Like a true Saison there is not a strong bitterness or aroma happening from the hop department.  Overall, I enjoyed this brew with its outdoorsy aroma and strong flavours.  It was enjoyably gross.",
            "Rogue New Crustacean Barleywineish Imperial IPA Sorta","wp-content/uploads/2014/02/Rogue-Crustacean-1024x682.jpg","Some say he once defeated Wolverine in an arm wrestling match and that wherever you are in the world, if you tune your radio to 88.4 you can actually hear his thoughts. All we know is, he's called The SWIG!","On 4 Mar 2014","Confusion sets in, as Live put it in the 90′s. So what was this then.  Let’s review in a Sherlock sort of way.  First of all, a royal blue bottle with a crab drawn by a third grader makes this bottle laughable, enjoyable and darling at the same time.  You have to buy this kinda like you have to pet that dog that comes up to you in a PLEASE pet me sort of way.  This brew poured an acceptable two finger head over an attractive hazy amber colour to boot.  Leaning IPA. The aroma was zesty and reminded me of a regular West Coast IPA, but there was also a sweetness and earthiness lingering which would be more Barleywine. Hmmm.  My tongue registered a viscous liquid with a slick mouthfeel finishing in a great smoothness. Hops were apparent from the citrus and herbal category up front, and they balanced out some bready caramel sweetness nicely.  The finish was grainy and piney and abrupt, if you call a paper cut abrupt.  It isn’t, and neither was that piney aftertaste which hung on the rest of the evening.  The verdict. Was it more barleywine than IPA, or vice versa? I suggest it was all imperial, started barleywine and finished IPA. Having said that, I also suggest labelling your tanks when doing transfers.",
            "Shatterbier Golden Ale"," ","Some say that his beard only grows on Wednesdays and that he fears only bad dates. All we know is, he's called The SWIG!","On 5 Jul 2013","Moon Under Water Shatterbier Golden Ale - This beer is a celebration of two found-only-in-Victoria businesses. I love these creations and Shatterbox is a good craft beer.  An enticing cloudy golden orange coloured beer is poured from a champagne bottle. why a champagne bottle?  it looks good and it’s cool.  The taste is surprising… good.  Coffee infused verified.  Delish! Boozy upfront, spice and coffee coming up in the nose, and as it warms a little, the coffee scent begins filling the air. Now some peaches and stone fruit.  The finish is dry and pleasant.  More carbonation would have improved it.  This is definite breakfast beer potential; the new mimosa. Birthday breakfast or a great way to start Mother’s or Father’s Day.  Thanks Moon.",
            "Sierra Nevada Northern Hemisphere Harvest","wp-content/uploads/2014/02/Sierra-Nevada-Northern-Hemisphere-1024x682.jpg","Some say he invented the Hail Mary and that he teaches needlepoint on the side. All we know is, He's called The SWIG!","On 20 Mar 2014","A fresh hop brew from Sierra Nevada of the Northern Hemisphere persuasion.  This begs the question on what their Southern Hemisphere Fresh Hop would taste like and how they would get those hops here without remortgaging the brewery.  Think about it, if you want to do something you may as well do it right.  On to beer!   This bomber beauty poured deep orange, and released a medicinal and herbal aroma.  I would also summarize as noble here.  As you may have read in previous reviews on fresh hopped beers, they tend to mellow the flavour out and give beers a more floral and noble character due to their higher moisture content.  This characteristic is exceptionally pleasing to this taster and the hard work is much appreciated.  The taste exhibited a slightly soapy or possibly lavender drift that was there and gone.  I did not like this as much; floral in the nose and not in the mouth please.  Mid-swig there was strong bitterness of the pine, wood, and plant persuasion which gave this brew American India pale ale character.  The finish was complete with no lingering flavours in my opinion so another sip was in order! Overall, this was a good beer to share and a good representative in the fresh hop style of brews.",
            "Sierra Nevada Tumbler","wp-content/uploads/2013/09/SN-tumbler-Swig-1024x682.jpg","Some say he can speak grasshopper and that he has not worn underwear in 13 years. All we know is, he's called The SWIG!","On 28 Sep 2013","This is a new product in BC as we have only recently been able to purchase Sierra Nevada products here. Yay!   A glass of this beer looks great with its deep brown and off-white  head.  The stocky bottle is always a pleasure to hold and empty as well.  The aroma comes off very subtle with only a little hop aroma to speak of and nothing else really.  Taste on the other hand is first smoky and dry, followed by  fruity and roasty.  The finish is papery, nutty and i guess nut-shelly, and there is strong bitterness that lingers between sips.  Harsh slightly….  The aroma and taste were very different, which is kind of a cool thing having two distinct experiences.  I was expecting some sweetness, but did not get any.  This beer was enjoyable and I am glad SN is up North. Thanks Sierra Nevada.",
            "Spaten Optimator Doppelbock","wp-content/uploads/2013/10/Photo12-1024x682.jpg","Some say he had a one night stand with Mary Poppins and that he invented suspenders. All we know is, he's called The SWIG!","On 22 Oct 2013","Ohhhh a Doppelbock.  This wonderful German creation is always welcome at the Swig tastings.  The aroma was stumping me at first but then I recalled a memory and there it was… grape juice.  Purple grape juice like Welch’s.  The colour is pure red loveliness.  Tasting is more complex.  There is a taste of grapey malt up front, so sweet and wort-like almost, then bitterness and a slight astringency comes second and lingers for a couple beats before juicy malt crashes into shores of alcoholic warmth.   The maltiness is great, and there is no hop aroma to speak of due to the grapey-raisiny-datey aroma being king.  I am not sure if this was what Spatenintended with their brew but that was my experience. Thanks Spaten.",
            "Stone Brewing IPA","wp-content/uploads/2013/10/Stone-IPA-1024x682.jpg","Some say he holds the keg toss record in Betherington, and that his bottle cap collection has its own postal code. All we know is, he's called The SWIG!","On 28 Oct 2013","Ohhhh a big time brewery from the USA once again.  So the legendary Stone IPA has come across the Swig’s bartop and is looking for validation.  Ok then.  We have a simply painted bottle with trademark gargoyle that is unmistakably of Greg Koch’s angry beers portfoloio.  The beer pours very nicely and shows a nice deep amber. A definite floral nose from our hoppy friends that fits well and is not over the top.  The taste comes across first as bitter, and it really hangs on for certain.  There is a juicy fruity taste that is difficult to describe except as juicy fruit really.  It is in fact a good and tasty brew, and I wish we had more brews like this in Canada.  A simple and pleasing IPA That could probably be considered angry a few years ago when it was launched, but now seems standard.  I suppose this is a testament to how far we have come regarding beer flavours.  Thanks Stone!",
            "Sv. Norbert speciálni svétlé pivo velikonocni","wp-content/uploads/2014/06/Sv.-Norbert2-1024x682.jpg","Some say he's fluent in 'Whale' and that he once ran a marathon in Crocs. All we know is he's called The SWIG!","On 27 Jun 2014","This is the first brew reviewed from the Czech Republic. There appears to be a craft brew scene growing there as well if this brewery has anything to say about the industry.  The bottle is a swing top type which gives it a homebrew feel and top quality at the same time… so counter. The label is simple and comical yet full of character in its Egyptian 2D platform.  The beer popped open so nicely and poured aerofoamatic- a tight white foam with growing effervescence. What is great about this brew is that it does not taste oxidized AT ALL like almost 100% of most other imports.  I imagine that has to do with the cloudiness and the yeast being alive and in suspension yet.  The beer has a great grainy smell, and outdoorsy.  The taste is crisp, and grassy, with a slight spice.  There is also some earthy quality that gives this brew full flavour.  A mystery flavour that I am going to say is tea leaves provides a slight tang on the back of the tongue.  It’s kind of a steamy fullness taste… not smoky.  The colour is an opaque amber that fits well with this brew. It is very drinkable and refreshing. Thanks St. Norbert!",
            "Swans Legacy Ale Barleywine"," ","Some say he's the world record holder for rolling a loop with a stick and that he can undo his velcro shoes without making a sound. All we know is he's called The SWIG!","On 7 Dec 2014","An annual homage to Michael Williams, this beer’s personality is almost as big as its namesake.  Mr. Williams was a well-reputed philanthropist in Victoria’s Old Town and only a robust and assertive beer would due to be his legacy.  This American Barleywine boasts big aromatic notes of figs, toasted almonds, currants and pie crust.  Once you let it past your nose and take a sip you’ll enjoy creme brule, burnt pumpkin seeds and sultana raisins from the roasty malt sweetness.  As it goes down a noticeable boozy warmth will keep you cozy like a warm sweater.  Enjoy this as a digestif, or with a good book by the fire.",
            "The Heretic","wp-content/uploads/2013/07/Heretic2-1024x682.jpg","Some say he was the only one who could out drink Andre the Giant and that he's now quite pickled. All we know is, he's called The SWIG!","On 7 Jul 2013","Driftwood Heretic Local Malt Tripel - Oh Driftwood. You are a beautifully successful brewery that really adds to this rich craft  fabric that Victoria is becoming.  Another Belgian? Great because you guys are good at this style.  So what happened this time?  This beer poured well with a lovely white foam and gorgeous golden yellow colour (on a side note, I love a beer that could fool an industrial lager drinker into pounding something and then run screaming for help). What else is delivered for your above average bomber price is a spicy nose,  apricots, breathy bitterness, and alcohol.  A sociable and stronger feeling than the posted 8% abv beer.  Counter to this goodness though is yeasty, vegetal, and resin flavours making it an unbalanced and rushed brew.  It is simply too sweet with too much body. Good for you for making this a local Belgian by using a local Saanich farmer and maltster though. Thanks for the experience.",
            "Tofino Tuff Session Ale","wp-content/uploads/2014/04/tofino-tuff-1024x682.jpg","Some say his followers are all called Pete and that he wears completely invisible underwear. All we know is, he's called The SWIG!","On 19 Apr 2014","Tofino brewing is a dream for a brewer.  You have local loyalty to your product and a feeling of a regional brewery.  This is how it is in Europe for the most part where a brewery rarely distributes past 50 km because it can be sustained there.  Whether Tofino is or not, we are lucky enough to taste Dave’s brews here in Victoria. My first impression of Tuff Session is its matte yet shiny label that caught the eye easily.  Adding to that a cool surfboard and there is no doubt this is a coastal brew targeted at a chill population.  Tuff pours a deep straw colour with slight haze and a foam that quickly dissipates.  The nose is bready with slight sweetness and taste is juicy and satisfying.  Midsip brings forward bitterness, and it is a well placed load of hops here. The nicely dry finish along with the pleasant aroma and assertive bitterness makes this a sessionable brew indeed.  I must admit that 5% seems to be a Canadian session strength since so many others are hitting that mark. It brings back a lot of the old jokes of the Canadian making the three or four stops at the American liquor store on a party weekend.  Overall enjoyable.",
            "Twisted Oak Barrel Aged Red Ale Phillips","wp-content/uploads/2013/10/photo3-1024x682.jpg","Some say he was the understudy for the Great Volare back when he was known as the Pretty Good Volare. All we know is he's called The SWIG!","On 7 Oct 2013","Phillips Twisted Oak Barrel Aged Red Ale - This brew pours out a ‘nailed-it’ red colour. Like Autumn red and orange.  The nose is full with caramel and vanilla and light molasses that feels coffee-like.  This beer tastes exactly how it smells. Full bodied warmth, warm licorice, warm toffee, sherry, and all this makes sense as this was aged in rum barrels.  The bitterness is subtle as it should be since the rum flavours are what matters here.  This beer is super enjoyable and great to share. Thanks again Phillips.",
            "VIB Surfrider Bohemian Pilsner","wp-content/uploads/2014/08/VIB-Surfrider-1024x682.jpg","Some say that he has a full size tattoo of his face on his face, and that he thought Star Wars was a documentry. All we know is he's called The SWIG!","On 5 Sep 2014","Vancouver Island brewery teamed up with The Surfrider Foundation charity to deliver a beer and cash to a worthy group of people. A Bohemian Pilsener is quite a task, but if anyone can do it in this town, VIB has the equipment.  The label is another choice in fun artwork, and again another stretch from the traditional ViB images, which is an acceptable change. The beer pours golden yellow with tinges of orange, and in my opinion, which I am being ‘paid’ to give, looks lovely.  The foam is burning white and fluffy, like clouds over Ogden Point with the sun blazing through.  What does the tongue say?  The Swig experiences tart maltiness, some grassiness, but not so much spiciness.  Further, there is grainy character, almost sprouted, with some straw thrown in the barrel.  This experience though is quick and then gone, like that. Snap! What lingers is a pleasant bitterness that is noble and herbal, with a peak of some new hop flavour that also rapidly vanishes.  It is an interesting brew that would be worthwhile exploring and enjoying on your own.  In fact, i would probably plan to finish this bomber on my own.  Thanks for stepping up the game VIB.",
            "VicFest Festival Ale","wp-content/uploads/2013/07/Photo11-1024x682.jpg","Some say he has a vast collection of brooms, and that he takes his coffee orange. All we know is he's called The SWIG!","On 5 Jul 2013","VicFest Festival Ale - The collaboration between Vancouver Island Brewery and this music festival now in its third shake is great.  Like the sounds of VicFest, the brew is crystal clear, riffed and fresh.  We get a super amber colour along with minimal vegetal aroma both being paired with slight fruitiness up front.  This rapid experience is quickly replaced with that lovely lager feeling although we are told it is ale.   In my honest opinion it would have benefitted from more prickly carbonation.  All told we are gifted an outdoor beer best enjoyed industrial cold, listening to music and able to enjoy all day, which I believe was its intent.  Although I feel they targeted more the  Nazareth crowd than the new grooves headlining.  Thanks VIB.",
            "Vivat Triple","wp-content/uploads/2013/07/Vivat-1024x682.jpg","Some say he has seen Smokey and the Bandit eleventeen times and that he invented November. All we know is, he's called The SWIG!","On 13 Jul 2013","A French brewery presenting a Belgian style… being a Canadian I am used to this scenario as I am sure you are too.  The bottle is magnificent with its ceramic material and heavy, full, round shape.  It gives the impression of thought and execution and that what is inside is special.  It did not even bother me when the cheap metal cage broke instead of twisting off nicely.  It pours well laying a coarse foam that lingers in the glass and a pale colour that fits well.  Sniffing like a dog I detect a welcome yeasty and peppery nose.  Having a first sip was in fact an occasion to smile and sigh.  Oh that tasted superb. It was dry and prickly and reminded me of caramelly pie even with the lingering warmth.  Richness that was experienced was swept off the tongue by the bubbles and dryness.  The high carbonation made it feel like champagne and sucking it like champagne only accentuated the spicy flavours. This beer made me feel wonderful, absolutely wonderful.  Merci, Vivat.",
            "Weißenoher Klosterbrauerei Bonator Doppelbock","wp-content/uploads/2013/09/Photo1-1024x682.jpg","Some say he is a world class curler and that he went to preschool with Ralph Macchio. All we know is, he's called The SWIG!","On 5 Sep 2013","Finally…Autumn (Well almost!).  This sweet and bready big bowl of bock has a roasted… nay scorched and wonderful caramelly flavour.  The nose smells of sweet spices and raisins (as it should) yet there is so much going on it’s almost hard to pinpoint.  It’s big and boozy, but even the alcohol is enjoyable to smell.  This beer feels so good to drink.  It smells complete and has a great bock aftertaste.  Finish isn’t too long and cuts off just at the right time enticing you for another sip.  It’s warming and to me is a like a big bearhug in a glass.  Definitely an excellent beer for sitting by the water on a chilly evening rocking a Dr. Huxtable sweater. Thanks Weißenoher",
            "2012 Westvleteren XII Belgian Quadruple","wp-content/uploads/2013/12/Westy-XII-1024x682.jpg","Some say he was the understudy for the Great Volare back when he was known as the Pretty Good Volare. All we know is he's called The SWIG!","On 26 Dec 2013","Ok so… there is a lot of hype around this beer.  ”Greatest beer in the world” is what I would call a lot of hype.  But that doesn’t mean it’s not true. In 2012 the monks of St. Sixtus in Westvleteren Belgium, decided to release this beer just one time to the world in order to raise money to restore their aging abbey.  So naturally this news set the beer geek community on fire and everyone was scrambling to get their giftset of 6 beers and 2 goblets. Since its release,  a year has past and I’ve shared and enjoyed 5 of them throughout 2013 and saved my last one for Christmas day this year.  And I must say it did not disappoint yet again.  Pouring with a rich, creamy mahogany head, you get a lot of that sweet/sticky fruits like dates, raisins and currants which all dance around with a bready fruitiness that all melds together beautifully. This is truly a complex and thoroughly enjoyable beer.  With 10.2% abv, Westy’s drinkability is surprising.  It’s amazing at how well the alcohol is hidden in such a delicate brew. So is paying $70 for a six pack worth it?  For an outstanding beer, that you will likely NEVER get a chance to try again and that’s been handcrafted by monks who have been doing it for centuries? I would say so.",
            "Wolf Black Tail Dark Malt Porter","wp-content/uploads/2013/11/Wolf-Dark-Malt-Porter-1024x682.jpg","Some say he's an expert knitter and that he discovered the Lanthanide series of elements. All we know is he's called The SWIG!","On 22 Nov 2013","One of a select few breweries that have found a way to survive up island delivers a big old porter. The beer pours a thick black that when held on the correct angle shows it is actually a very deep brown.  I love that colour.  The nose is tobacco, molasses, coffee, and a great raisiny touch.  This is a nice complex olfactory trip.  The taste is malty sweet and very drying. No real fruitiness or estery notes, just malty with a slight chalkiness.  The carbonation is really nice too… almost too high, but a nice scrub. Overall, a nice tasty brew that feels great. I like it. Enjoyable. Thanks Wolf."]
        var hackone=0
        while(hackone<290){
            let tempSwigName = swigReviews[hackone]
            let tempSwigImage = swigReviews[hackone+1]
            let tempSwigLine = swigReviews[hackone+2]
            let tempSwigDate = swigReviews[hackone+3]
            let tempSwigReview = swigReviews[hackone+4]
            hackone+=5
            self.swigData.append(swigName:tempSwigName,
                swigImage:tempSwigImage,
                swigLine:tempSwigLine,
                swigDate:tempSwigDate,
                swigReview:tempSwigReview)
        }
        }

    /*
    // MARK: - Navigation

    // In a storyboard-based application, you will often want to do a little preparation before navigation
    override func prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?) {
        // Get the new view controller using segue.destinationViewController.
        // Pass the selected object to the new view controller.
    }
    */

}
